/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#00714d",
        "on-secondary-fixed-variant": "#005236",
        "on-tertiary-container": "#7dc406",
        "primary-container": "#064e3b",
        "electric-lime": "#A3E635",
        "on-primary-fixed-variant": "#0b513d",
        "tertiary-fixed": "#acf847",
        "secondary-container": "#6cf8bb",
        "error-container": "#ffdad6",
        "on-primary-container": "#80bea6",
        "primary": "#003527",
        "on-tertiary-fixed-variant": "#304f00",
        "secondary": "#006c49",
        "surface-container-high": "#e2e7ff",
        "tertiary-fixed-dim": "#91db2a",
        "on-secondary": "#ffffff",
        "primary-fixed": "#b0f0d6",
        "surface-variant": "#dae2fd",
        "inverse-on-surface": "#eef0ff",
        "secondary-fixed-dim": "#4edea3",
        "card-border": "#E2E8F0",
        "on-background": "#131b2e",
        "surface-container-low": "#f2f3ff",
        "primary-fixed-dim": "#95d3ba",
        "surface-dim": "#d2d9f4",
        "outline-variant": "#bfc9c3",
        "inverse-surface": "#283044",
        "surface-bright": "#faf8ff",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#6ffbbe",
        "inverse-primary": "#95d3ba",
        "tertiary-container": "#2d4c00",
        "tertiary": "#1d3400",
        "on-primary-fixed": "#002117",
        "on-surface": "#131b2e",
        "slate-muted": "#64748B",
        "background": "#faf8ff",
        "surface": "#faf8ff",
        "mint-surface": "#F0FDF4",
        "sun-amber": "#F59E0B",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#102000",
        "on-secondary-fixed": "#002113",
        "surface-container": "#eaedff",
        "error": "#ba1a1a",
        "outline": "#707974",
        "surface-tint": "#2b6954",
        "on-surface-variant": "#404944",
        "deep-canopy": "#022C22",
        "surface-container-highest": "#dae2fd"
      },
      fontFamily: {
        "headline-hero": ["Outfit", "sans-serif"],
        "headline-hero-mobile": ["Outfit", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "headline-sm": ["Outfit", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-interactive": ["Inter", "sans-serif"],
        "label-badge": ["Space Grotesk", "sans-serif"],
        "label-metric": ["Space Grotesk", "sans-serif"]
      },
      fontSize: {
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-interactive": ["15px", { lineHeight: "20px", fontWeight: "600" }],
        "label-badge": ["12px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-metric": ["32px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }]
      }
    }
  },
  plugins: []
};
